name: Windows Basic Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  
  windows:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'windows')  &&
      contains(github.event.pull_request.labels.*.name, 'azure') 

    steps:

    - name: Create instance
      run: |
        podman run -d --name windows-create --rm \
        -v ${PWD}:/workspace:z \
        -e ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} \
        -e ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} \
        -e ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }} \
        -e ARM_CLIENT_SECRET='${{ secrets.ARM_CLIENT_SECRET }}' \
        quay.io/rhqp/qenvs:v0.0.4-snapshot azure \
          windows create \
          --project-name 'windows-desktop' \
          --backed-url 'file:///workspace' \
          --conn-details-output '/workspace' \
          --windows-version '11' \
          --windows-featurepack '22h2-ent' \
          --vmsize 'Standard_D8a_v4'


    - name: View windows creation logs
      continue-on-error: true
      run: |
        podman logs -f windows-create

    - name: Check instance system info
      continue-on-error: true
      run: |
        set -xuo
        ssh -i id_rsa \
          -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          -o ServerAliveInterval=30 \
          -o ServerAliveCountMax=1200 \
          $(cat username)@$(cat host) "systeminfo"

    - name: Emulate X session 
      continue-on-error: true
      run: |
        # use fake rdp to emulate an active x session
        podman run -d --name x-session \
          -e RDP_HOST=$(cat host) \
          -e RDP_USER=$(cat username) \
          -e RDP_PASSWORD=$(cat userpassword) \
          -e DEBUG=true \
          quay.io/rhqp/frdp:v0.0.1
        # Wait until the x session has been created
        podman wait --condition running x-session
        # Check logs for the x session
        podman logs x-session

    - name: Destroy instance
      run: |
        podman run -d --name windows-destroy --rm \
        -v ${PWD}:/workspace:z \
        -e ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} \
        -e ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} \
        -e ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }} \
        -e ARM_CLIENT_SECRET='${{ secrets.ARM_CLIENT_SECRET }}' \
        quay.io/rhqp/qenvs:v0.0.4-snapshot azure \
          windows destroy \
          --project-name 'windows-desktop' \
          --backed-url 'file:///workspace'
        
    - name: View instance destroy logs
      run: |
        podman logs -f windows-destroy


